package routers

import (
	"firstDemo/controllers"
	"github.com/astaxie/beego"
)

func init() {
	beego.Router("/", &controllers.MainController{})
	beego.Router("/user", &controllers.UserController{})
	beego.Router("/dodlogin", &controllers.DoctorLoginController{}, "POST:Login")
	beego.Router("/doctorLogin", &controllers.DoctorLoginController{})
	beego.Router("/doctorRegister", &controllers.DoctorRegisterController{})
	beego.Router("/dodregister", &controllers.DoctorRegisterController{}, "POST:Register")
	beego.Router("/mainpage", &controllers.MainPageController{})
	beego.Router("/doctorList", &controllers.DoctorListController{})
	beego.Router("/getall", &controllers.DoctorListController{}, "GET:GetAll")
	beego.Router("/deleteDoctor/:id", &controllers.DoctorListController{}, "DELETE:DeleteDoctor")
	beego.Router("/updateusers/:id", &controllers.UpdateDoctorController{})
	beego.Router("/doupdateusers", &controllers.UpdateDoctorController{}, "PUT:UpdateUsers")
	beego.Router("/page", &controllers.DoctorListController{}, "POST:ShowDoctorByPage")
	beego.Router("/getlist", &controllers.DoctorListController{}, "GET:GetDoctorList")
	beego.Router("/showlist", &controllers.DoctorListController{}, "POST:ShowList")
	beego.Router("/selectdoctor", &controllers.DoctorListController{}, "POST:SelectDoctor")
	beego.Router("/reservation", &controllers.ReservationController{})
	beego.Router("/getallreservation", &controllers.ReservationController{}, "GET:GetReservation")
	beego.Router("/selectreservation", &controllers.ReservationController{}, "POST:SelectReservation")
	beego.Router("/findbyname/:id", &controllers.ReservationController{}, "GET:FindByName")
	beego.Router("/patientSystem", &controllers.PatientSystemController{})
	beego.Router("/personalCenter", &controllers.PersonalCenterController{})
	beego.Router("/getone", &controllers.PersonalCenterController{}, "GET:GetOne")
	beego.Router("/patientRegister", &controllers.PatientRegisterController{})
	beego.Router("/dopregister", &controllers.PatientRegisterController{}, "POST:Register")
	beego.Router("/doplogin", &controllers.PatientLoginController{}, "POST:Login")
	beego.Router("/patientLogin", &controllers.PatientLoginController{})
	beego.Router("/doctorSystem", &controllers.DoctorSystemController{})
	beego.Router("/checkCard", &controllers.CheckCardController{})
	beego.Router("/getcheckcard", &controllers.CheckCardController{}, "GET:GetCheckCard")
	beego.Router("/choosecheckcard/:id", &controllers.CheckCardController{}, "POST:Choose")
	beego.Router("/selectcheckcard", &controllers.CheckCardController{}, "POST:SelectCheckCard")
	beego.Router("/checkResult", &controllers.CheckResultController{})
	beego.Router("/getcheckresult", &controllers.CheckResultController{}, "GET:GetCheckResult")
	beego.Router("/selectcheckresult", &controllers.CheckResultController{}, "POST:SelectCheckResult")
	beego.Router("/getpname/:id", &controllers.CheckResultController{}, "GET:GetPname")
	beego.Router("/deletecheckresult/:id", &controllers.CheckResultController{}, "DELETE:DeleteCheckResult")
	beego.Router("/updatecheckresult", &controllers.UpdateCheckResultController{})
	beego.Router("/getupdatecheckcard", &controllers.UpdateCheckResultController{}, "GET:GetUpdateCheckCard")
	beego.Router("/updatecheckresult/:id", &controllers.UpdateCheckResultController{}, "POST:UpdateCheckResult")
	beego.Router("/patientReservate", &controllers.PatientReservateController{})
	beego.Router("/doreservate", &controllers.PatientReservateController{}, "POST:GetReservate")
	beego.Router("/reservateInformation", &controllers.ReservateInformationController{})
	beego.Router("/getreservate", &controllers.ReservateInformationController{}, "GET:GetOneReservate")
	beego.Router("/deletereservate/:id", &controllers.ReservateInformationController{}, "DELETE:DeleteReservate")
	beego.Router("/checkNone", &controllers.CheckNoneController{})
	beego.Router("/getchecknone", &controllers.CheckNoneController{}, "GET:GetCheckNone")
	beego.Router("/updateReservate/:id", &controllers.UpdateReservateController{})
	beego.Router("/updatereservate", &controllers.UpdateReservateController{}, "PUT:UpdateReservate")
	beego.Router("/patientList", &controllers.PatientListController{})
	beego.Router("/getallpatient", &controllers.PatientListController{}, "GET:GetAllPatient")
	beego.Router("/selectpatient", &controllers.PatientListController{}, "POST:SelectPatient")
	beego.Router("/deletepatient/:id", &controllers.PatientListController{}, "DELETE:DeletePatient")
	beego.Router("/updatePatient/:id", &controllers.UpdatePatientController{})
	beego.Router("/doupdatepatient", &controllers.UpdatePatientController{}, "PUT:UpdatePatient")
	beego.Router("/managerRegister", &controllers.ManagerRegisterController{})
	beego.Router("/domregister", &controllers.ManagerRegisterController{}, "POST:Register")
	beego.Router("/managerLogin", &controllers.ManagerLoginController{})
	beego.Router("/domlogin", &controllers.ManagerLoginController{}, "POST:Login")
	beego.Router("/managerSystem", &controllers.ManagerSystemController{})
}
